# Project Public Identifier: joomla-official-extensions
project_id: 102
api_token_env: CROWDIN_PERSONAL_TOKEN
base_path: 
base_url: "https://joomla.crowdin.com"

preserve_hierarchy: true

files:
  - source: /Brochures/Joomla4/en-GB/joomla4-2021.idml
    dest: 'Brochures/joomla4-2021.idml'
    translation: /Brochures/Joomla4/%locale%/joomla4-2021.idml
    type: idml
    
  - source: /Videos/Joomla4/en-GB/j4release.srt
    dest: 'Videos/j4release.srt'
    translation: /Videos/Joomla4/%locale%/j4release.srt
    type: srt
